### ISSUE TITLE
Make messages more configurable

### ISSUE THREAD

**Issue by FireML** [FireML-Dev/DaisyLib#45]
The current message format in configs is like so:
```yaml
example-message: "My Message"
```

I will update it to allow this type of configuration along with its current format:
```yaml
example-message:
  type: chat/action_bar/title/subtitle
  message: "My Message"
```
